name: Cppcheck

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/cppcheck.yml'
  pull_request:
    branches: [ master ]

jobs:
  cppcheck:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    permissions:
      actions:         read
      contents:        read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake cppcheck \
                                  pkg-config libcurl4-openssl-dev libuv1-dev \
                                  libgtest-dev nlohmann-json3-dev rapidjson-dev

      - name: Build
        run: |
          cmake -B         build/  -DCMAKE_BUILD_TYPE=Release

      - name: Run Cppcheck on sources
        run: |
          cmake --build build/  --config Release  --target cppcheck
